# Generated by Django 5.0.1 on 2026-02-09 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('name', models.CharField(help_text="Nome do ambiente (ex: 'Desenvolvimento', 'Produção')", max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='URL-friendly name (gerado automaticamente)', max_length=100, verbose_name='Slug')),
                ('base_url', models.URLField(help_text='URL base do ambiente (ex: https://dev.tjgo.jus.br)', max_length=500, verbose_name='URL Base')),
                ('env_type', models.CharField(choices=[('development', 'Desenvolvimento'), ('staging', 'Homologação'), ('production', 'Produção')], default='development', help_text='Tipo do ambiente', max_length=20, verbose_name='Tipo de Ambiente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_remover', to=settings.AUTH_USER_MODEL, verbose_name='Deletado por')),
                ('project', models.ForeignKey(help_text='Projeto ao qual este ambiente pertence', on_delete=django.db.models.deletion.PROTECT, related_name='environments', to='projects.project', verbose_name='Projeto')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['project', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['project', 'is_active'], name='environment_project_4c2863_idx'), models.Index(fields=['env_type'], name='environment_env_typ_3e6a9f_idx'), models.Index(fields=['name'], name='environment_name_9f6be9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'name'), name='unique_environment_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'slug'), name='unique_environment_slug_per_project'),
        ),
    ]
