# Generated by Django 5.0.1 on 2026-02-20 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
        ('projects', '0002_alter_project_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ['project', 'env_type'], 'verbose_name': 'Ambiente', 'verbose_name_plural': 'Ambientes'},
        ),
        migrations.RemoveConstraint(
            model_name='environment',
            name='unique_environment_name_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='environment',
            name='unique_environment_slug_per_project',
        ),
        migrations.RemoveIndex(
            model_name='environment',
            name='environment_name_9f6be9_idx',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='slug',
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'env_type'), name='unique_environment_type_per_project'),
        ),
    ]
