# Generated by Django 5.0.1 on 2026-02-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text='URL-friendly name (gerado automaticamente)', max_length=255, verbose_name='Slug'),
        ),
    ]
