# Generated by Django 5.0.1 on 2026-02-16 23:07

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Nome único da tag (ex: 'Login', 'Crítico')", max_length=50, unique=True, verbose_name='Nome')),
                ('color', models.CharField(default='#007bff', help_text='Cor em hexadecimal para badges (ex: #007bff)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor')),
                ('description', models.TextField(blank=True, help_text='Descrição opcional da tag', verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='tags_tag_name_3fbe74_idx')],
            },
        ),
    ]
