# Generated by Django 5.0.1 on 2026-02-16 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        ('projects', '0002_alter_project_slug'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('run_id', models.CharField(help_text="ID único da execução (ex: 'run-20260214-001')", max_length=100, unique=True, verbose_name='ID da Execução')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Em Execução'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('api', 'API (CI/CD)'), ('scheduled', 'Agendado')], default='api', max_length=20, verbose_name='Tipo de Disparo')),
                ('branch', models.CharField(blank=True, help_text="Branch Git (ex: 'main', 'develop')", max_length=255, verbose_name='Branch')),
                ('commit_sha', models.CharField(blank=True, help_text='Hash do commit Git', max_length=40, verbose_name='Commit SHA')),
                ('commit_message', models.TextField(blank=True, verbose_name='Mensagem do Commit')),
                ('total_tests', models.IntegerField(default=0, verbose_name='Total de Testes')),
                ('passed_tests', models.IntegerField(default=0, verbose_name='Testes Aprovados')),
                ('failed_tests', models.IntegerField(default=0, verbose_name='Testes Falhados')),
                ('skipped_tests', models.IntegerField(default=0, verbose_name='Testes Pulados')),
                ('flaky_tests', models.IntegerField(default=0, verbose_name='Testes Instáveis')),
                ('duration_seconds', models.FloatField(default=0.0, verbose_name='Duração (segundos)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_remover', to=settings.AUTH_USER_MODEL, verbose_name='Deletado por')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='environments.environment', verbose_name='Ambiente')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='projects.project', verbose_name='Projeto')),
                ('tags', models.ManyToManyField(blank=True, related_name='test_runs', to='tags.tag', verbose_name='Tags')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs_triggered', to=settings.AUTH_USER_MODEL, verbose_name='Disparado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Execução de Teste',
                'verbose_name_plural': 'Execuções de Teste',
                'ordering': ['-started_at', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['project', 'environment', '-started_at'], name='runs_testru_project_58e0d0_idx'), models.Index(fields=['run_id'], name='runs_testru_run_id_b87389_idx'), models.Index(fields=['status'], name='runs_testru_status_8810f1_idx'), models.Index(fields=['branch'], name='runs_testru_branch_608d7b_idx'), models.Index(fields=['-started_at'], name='runs_testru_started_6059ec_idx')],
            },
        ),
    ]
