# Generated by Django 5.0.1 on 2026-02-16 23:07

import apps.cases.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_project_slug'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('case_id', models.CharField(help_text='ID único do caso no projeto (ex: TC-001)', max_length=50, verbose_name='ID do Caso')),
                ('title', models.CharField(help_text='Título descritivo do caso de teste', max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(help_text='URL-friendly name (gerado automaticamente)', max_length=255, verbose_name='Slug')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('ACTIVE', 'Ativo'), ('DEPRECATED', 'Depreciado')], default='DRAFT', help_text='Status atual do caso de teste', max_length=20, verbose_name='Status')),
                ('module', models.CharField(blank=True, help_text="Módulo ou funcionalidade (ex: 'Autenticação', 'Processos')", max_length=100, verbose_name='Módulo')),
                ('objective', models.TextField(blank=True, help_text='O que este teste valida?', verbose_name='Objetivo')),
                ('preconditions', models.TextField(blank=True, help_text='Estado necessário antes da execução', verbose_name='Pré-condições')),
                ('postconditions', models.TextField(blank=True, help_text='Estado esperado após a execução', verbose_name='Pós-condições')),
                ('expected_result', models.TextField(blank=True, help_text='Resultado esperado do teste', verbose_name='Resultado Esperado')),
                ('observations', models.TextField(blank=True, help_text='Observações gerais, notas, etc.', verbose_name='Observações')),
                ('test_title', models.CharField(blank=True, help_text='Título exato do test() no código Playwright', max_length=255, verbose_name='Título no Playwright')),
                ('playwright_id', models.CharField(blank=True, help_text="ID único para vincular com código (ex: 'auth-login-valid')", max_length=255, null=True, verbose_name='Playwright ID')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_remover', to=settings.AUTH_USER_MODEL, verbose_name='Deletado por')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases_modified', to=settings.AUTH_USER_MODEL, verbose_name='Última modificação por')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='projects.project', verbose_name='Projeto')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags para categorização', related_name='test_cases', to='tags.tag', verbose_name='Tags')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Caso de Teste',
                'verbose_name_plural': 'Casos de Teste',
                'ordering': ['project', 'case_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCaseAttachment',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('file', models.FileField(upload_to=apps.cases.models.test_case_attachment_path, verbose_name='Arquivo')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('attachment_type', models.CharField(choices=[('IMAGE', 'Imagem'), ('DOCUMENT', 'Documento'), ('OTHER', 'Outro')], default='IMAGE', max_length=20, verbose_name='Tipo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_remover', to=settings.AUTH_USER_MODEL, verbose_name='Deletado por')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.testcase', verbose_name='Caso de Teste')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Anexo de Caso de Teste',
                'verbose_name_plural': 'Anexos de Casos de Teste',
                'ordering': ['test_case', 'order'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['project', 'status', 'is_active'], name='cases_testc_project_45b97d_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['playwright_id'], name='cases_testc_playwri_b3b1e5_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['module'], name='cases_testc_module_ebd311_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['case_id'], name='cases_testc_case_id_d50c74_idx'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'case_id'), name='unique_case_id_per_project'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('playwright_id__isnull', False)), fields=('playwright_id',), name='unique_playwright_id'),
        ),
    ]
