# Generated by Django 5.0.1 on 2026-05-09 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('kanban', '0001_initial'),
        ('projects', '0002_alter_project_slug'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='board_position',
            field=models.PositiveIntegerField(default=0, help_text='Ordem dentro da coluna (0 = primeiro)', verbose_name='Posição no board'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='kanban_column',
            field=models.ForeignKey(blank=True, help_text='Coluna do board onde este caso está posicionado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='kanban.kanbancolumn', verbose_name='Coluna Kanban'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['kanban_column', 'board_position'], name='cases_testc_kanban__b2178a_idx'),
        ),
    ]
