# Generated by Django 5.0.1 on 2026-05-09 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_testcase_board_position_testcase_kanban_column_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável por este caso de teste', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='priority',
            field=models.CharField(choices=[('CRITICAL', 'Crítica'), ('HIGH', 'Alta'), ('MEDIUM', 'Média'), ('LOW', 'Baixa')], default='MEDIUM', help_text='Prioridade do caso de teste', max_length=20, verbose_name='Prioridade'),
        ),
    ]
