# Generated by Django 5.0.1 on 2026-05-19 20:16

import apps.cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_testcase_assigned_to_testcase_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.cases.models.test_case_attachment_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='testcaseattachment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Título'),
        ),
    ]
