# Generated by Django 5.0.1 on 2026-05-26 23:06

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_testcaseattachment_file_and_more'),
        ('projects', '0002_alter_project_slug'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTestCase',
            fields=[
                ('pkid', models.BigIntegerField(blank=True, db_index=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Criado em')),
                ('case_id', models.CharField(help_text='ID único do caso no projeto (ex: TC-001)', max_length=50, verbose_name='ID do Caso')),
                ('title', models.CharField(help_text='Título descritivo do caso de teste', max_length=255, verbose_name='Título')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('ACTIVE', 'Ativo'), ('DEPRECATED', 'Depreciado')], default='DRAFT', help_text='Status atual do caso de teste', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Crítica'), ('HIGH', 'Alta'), ('MEDIUM', 'Média'), ('LOW', 'Baixa')], default='MEDIUM', help_text='Prioridade do caso de teste', max_length=20, verbose_name='Prioridade')),
                ('module', models.CharField(blank=True, help_text="Módulo ou funcionalidade (ex: 'Autenticação', 'Processos')", max_length=100, verbose_name='Módulo')),
                ('objective', models.TextField(blank=True, help_text='O que este teste valida?', verbose_name='Objetivo')),
                ('preconditions', models.TextField(blank=True, help_text='Estado necessário antes da execução', verbose_name='Pré-condições')),
                ('postconditions', models.TextField(blank=True, help_text='Estado esperado após a execução', verbose_name='Pós-condições')),
                ('expected_result', models.TextField(blank=True, help_text='Resultado esperado do teste', verbose_name='Resultado Esperado')),
                ('observations', models.TextField(blank=True, help_text='Observações gerais, notas, etc.', verbose_name='Observações')),
                ('test_title', models.CharField(blank=True, help_text='Título exato do test() no código Playwright', max_length=255, verbose_name='Título no Playwright')),
                ('playwright_id', models.CharField(blank=True, help_text="ID único para vincular com código (ex: 'auth-login-valid')", max_length=255, null=True, verbose_name='Playwright ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário responsável por este caso de teste', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='Projeto')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'historical Caso de Teste',
                'verbose_name_plural': 'historical Casos de Teste',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTestCase_tags',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='cases.historicaltestcase')),
                ('tag', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tags.tag')),
                ('testcase', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.testcase')),
            ],
            options={
                'verbose_name': 'HistoricalTestCase_tags',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTestCaseAttachment',
            fields=[
                ('pkid', models.BigIntegerField(blank=True, db_index=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Criado em')),
                ('file', models.TextField(blank=True, max_length=100, null=True, verbose_name='Arquivo')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('attachment_type', models.CharField(choices=[('IMAGE', 'Imagem'), ('DOCUMENT', 'Documento'), ('OTHER', 'Outro')], default='IMAGE', max_length=20, verbose_name='Tipo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('test_case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.testcase', verbose_name='Caso de Teste')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('uploaded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'historical Anexo de Caso de Teste',
                'verbose_name_plural': 'historical Anexos de Casos de Teste',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
