# Generated by Django 5.0.1 on 2026-02-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_login_accomplished',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_emails',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Nome do usuário', max_length=30, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Sobrenome do usuário', max_length=150, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, verbose_name='Está ativo?'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
