# Generated by Django 5.0.1 on 2026-02-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='user_reset_password_subject',
            field=models.CharField(default='Atualizar senha - TJGOhub', max_length=255, verbose_name='Atualizar senha (subject)'),
        ),
        migrations.AlterField(
            model_name='email',
            name='user_welcome_subject',
            field=models.CharField(default='Bem-vindo - TJGOhub', max_length=255, verbose_name='Novo usuário (subject)'),
        ),
    ]
