# Generated by Django 5.0.1 on 2026-05-09 03:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_project_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('name', models.CharField(help_text="Nome da coluna (ex: 'Backlog', 'In Progress')", max_length=100, verbose_name='Nome')),
                ('color', models.CharField(default='#6366f1', help_text='Cor da coluna em hexadecimal (ex: #6366f1)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor')),
                ('order', models.PositiveIntegerField(default=0, help_text='Posição horizontal no board (0 = primeira coluna)', verbose_name='Ordem')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_remover', to=settings.AUTH_USER_MODEL, verbose_name='Deletado por')),
                ('project', models.ForeignKey(blank=True, help_text='Projeto ao qual pertence. Nulo = coluna global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_columns', to='projects.project', verbose_name='Projeto')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Coluna Kanban',
                'verbose_name_plural': 'Colunas Kanban',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
