# Generated by Django 5.0.1 on 2026-02-16 23:07

import apps.artifacts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('artifact_type', models.CharField(choices=[('SCREENSHOT', 'Screenshot'), ('VIDEO', 'Vídeo'), ('TRACE', 'Trace do Playwright'), ('LOG', 'Log')], max_length=20, verbose_name='Tipo de Artefato')),
                ('file', models.FileField(max_length=500, upload_to=apps.artifacts.models.artifact_upload_path, verbose_name='Arquivo')),
                ('file_name', models.CharField(help_text='Nome original do arquivo', max_length=255, verbose_name='Nome do Arquivo')),
                ('file_size', models.BigIntegerField(help_text='Tamanho em bytes', verbose_name='Tamanho do Arquivo')),
                ('mime_type', models.CharField(blank=True, help_text='Tipo de conteúdo (image/png, video/webm, etc)', max_length=100, verbose_name='MIME Type')),
                ('title', models.CharField(help_text='Título descritivo do artefato', max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descrição opcional', verbose_name='Descrição')),
                ('thumbnail_path', models.CharField(blank=True, help_text='Preview do artefato (se aplicável)', max_length=500, verbose_name='Caminho do Thumbnail')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_remover', to=settings.AUTH_USER_MODEL, verbose_name='Deletado por')),
            ],
            options={
                'verbose_name': 'Artefato de Teste',
                'verbose_name_plural': 'Artefatos de Teste',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
